baseURL = "https://odu-cga-cubesat.github.io/dilophos"
title = "DilophOS"
theme = "geekdoc"
pygmentsUseClasses = true
pygmentsCodeFences = true
timeout = 180000
pluralizeListTitles = false

# Geekdoc configuration
disablePathToLower = false
enableGitInfo = false

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe  = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
  [markup.asciidocext]
    extensions  = ["asciidoctor-diagram"]
    workingFolderCurrent  = true
    trace  = true

[params]
  # geekdocMenuBundle = true
  geekdocToC = 3

  geekdocRepo = "https://github.com/odu-cga-cubesat/dilophos"
  geekdocEditPath = "edit/main/docs/content"

  geekdocSearch = true
  geekdocSearchShowParent = true

  geekdocImageLazyLoading = true
